CREATE TABLE employees (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(200) DEFAULT NULL,
  cpf VARCHAR(200) DEFAULT NULL,
  data_nascimento DATE DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  data_cadastro DATETIME DEFAULT CURRENT_TIMESTAMP(),
  data_deleted DATE DEFAULT NULL,
PRIMARY KEY (`id`)
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4

